import{i as c,S as l}from"./assets/vendor-8501dee5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const d="44070531-25bb98da1641556d9bb7c94d1";async function u(n){const o=`https://pixabay.com/api/?key=${d}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const e=await fetch(o);if(!e.ok)throw new Error("Network response was not ok");return(await e.json()).hits}catch(e){throw console.error("Error fetching data:",e),e}}function f(){const n=document.querySelector(".gallery");n.innerHTML=""}function m(n){const o=document.querySelector(".gallery");if(n.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}n.forEach(e=>{const s=document.createElement("a");s.href=e.largeImageURL,s.classList.add("card"),s.innerHTML=`
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      <div class="card-info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    `,o.appendChild(s)}),new l(".gallery a").refresh()}function p(){document.querySelector(".loader").style.display="block"}function i(){document.querySelector(".loader").style.display="none"}const y=document.querySelector("#search-form"),h=document.querySelector("#search-input");y.addEventListener("submit",g);function g(n){n.preventDefault();const o=h.value.trim();if(o===""){c.error({title:"Error",message:"Please enter a search term."});return}f(),p(),u(o).then(e=>{i(),m(e)}).catch(e=>{i(),console.error("Error searching for images:",e),c.error({title:"Error",message:"Failed to load images. Please try again later."})})}
//# sourceMappingURL=commonHelpers.js.map
